slack:
  bot_token: "${SLACK_BOT_TOKEN}"
  signing_secret: "${SLACK_SIGNING_SECRET}"
  app_token: "${SLACK_APP_TOKEN}"
  client_id: "${SLACK_CLIENT_ID}"
  client_secret: "${SLACK_CLIENT_SECRET}"
  

firebase:
  project_id: "slack-attendance-bot-4a3a5"
  credentials_path: "config/firebase-credentials.json"

application:
  timezone: "Asia/Tokyo"
  
attendance_alerts:
  enabled: False
  long_work_warning_minutes: 480  # 8時間以上勤務でアラート
  long_break_warning_minutes: 120  # 1時間以上休憩でアラート
  check_interval_minutes: 30     # 30分ごとにチェック